version: "{build}"
image: Visual Studio 2019
configuration: Release

build_script:
- cmd: PowerShell .\build.ps1 -Target=Pack

artifacts:
- path: build\packages\*.nupkg

skip_commits:
  files:
  - LICENSE
  - README.md

test: off
